# Generated by Django 6.0 on 2026-01-15 10:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('glass_background', models.CharField(default='rgba(255,255,255,0.08)', max_length=20)),
                ('glass_border_color', models.CharField(default='rgba(255,255,255,0.25)', max_length=20)),
                ('featured_title', models.CharField(default='Featured Classics', max_length=100)),
            ],
            options={
                'verbose_name': 'Theme & Site Settings',
                'verbose_name_plural': 'Theme & Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
